#!/usr/bin/env php
<?php
	require __DIR__ . '/vendor/autoload.php';

    # Class Importer
    spl_autoload_register(function ($class) {
        $path = lcfirst(str_replace('\\', '/', $class)) . '.php';
        if (file_exists($path)) {
            require_once $path;
        }
    });

	$application = App\Bootstrap\Application::boot();
	$application->withEnvironment(base_path('.env'));
	$application->withConfiguration(base_path('app/Config.php'));
    $application->run(fn() => launch_cli_session($argv, 'commands', './'));

