#!/usr/bin/env php
<?php

    use App\Bootstrap\Application;

    require __DIR__ . '/vendor/autoload.php';

    # Class Importer
    spl_autoload_register(function ($class) {
        $path = lcfirst(str_replace('\\', '/', $class)) . '.php';
        if (file_exists($path)) {
            require_once $path;
        }
    });

    Application::boot(base_path('.env'))->run(fn() => launch_cli_session($argv, 'commands', './'));

