#!/usr/bin/env php
<?php
    # To perform scheduler
    define('APP_SCHEDULER', true);

    use App\Console\Terminal;
    use App\Console\Schedule;
    require __DIR__ . '/vendor/autoload.php';

    # Class Importer
    spl_autoload_register(function ($class) {
        $path = lcfirst(str_replace('\\', '/', $class)) . '.php';
        if (file_exists($path)) {
            require_once $path;
        }
    });

    $application = App\Bootstrap\Application::boot();
    $application->withEnvironment('.env');
    $application->withConfiguration('app/Config.php');
    $application->run(function() use($argv) {
        Terminal::config('commands', './');
        Schedule::execute();
    });

